### PR TITLE
Fix doc to spec

### PR DESCRIPTION
**Pull request by jrmlhermitte**
We need to fix document to spec.
We inherit from `CallBackBase` but never call super!

We need to inherit the new `resource` and `datum` methods

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
getting errors i think are unrelated in py3.5
otherwise py3.6 passes

```
jsonschema.exceptions.ValidationError: (('time',), 'primary') is not of type 'array'
```

**Comment by danielballan** [comment]
I wonder jsonschema does consider tuples of mixed type (in this case, an inner tuple and a string) an "array".

**Comment by tacaswell** [comment]
'powercycled' to get new version of event-model.  This may fix the validation error.

It may also be that we are only building conda packages for 3.6 so the 3.5 build is getting an different version of event-model.

**Comment by tacaswell** [comment]
Yeah, we are getting em 1.4 something on py3.5 and we need em 1.5 which includes both the resource/datum documents and a tweak to what we ask the validator to consider 'an array'.

**Comment by danielballan** [comment]
See https://github.com/NSLS-II/suitcase-specfile

**Pull request closed without merging**
